using Microsoft.AspNetCore.Mvc;

namespace SAW.Web.Api.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TasksController : ControllerBase
    {
        private readonly ILogger<TasksController> _logger;

        public TasksController(ILogger<TasksController> logger)
        {
            _logger = logger;
        }
        // TODO Create Tasks
        // TODO Create AutoGenerated Tasks
        // TODO Get Tasks
        // TODO Assign Tasks
        // TODO Delete Tasks
    }
}
